# Вправи
(використовувати тільки матричні операції)

1. Отримати суму елементів та суму квадратів елементів вектора:

In [2]:
import numpy as np

x = np.array([1, 2, 3])
y = np.ones(len(x))

print(x @ y)
print(x * x @ y)

6.0
14.0


2. Для вектора попереднього завдання побудувати вектор, кожним елементом якого є середнє значення вектора.

In [3]:
print((x @ y / (y @ y)) * y )

[2. 2. 2.]


3. Написати функцію, яка приймає на вхід довільну кількість матриць, перевіряє, чи можна їх перемножити, і якщо можна, то повертає розмірність результату (можна скористатися циклом). 

In [14]:
def check(*matrices):
    dim = list(matrices[0].shape)
    for i in range(1, len(matrices)):
        if dim[1] == matrices[i].shape[0]:
            dim = [dim[0], matrices[i].shape[1]]
        else:
            return False
    else:
        return True, dim


A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
D = np.array([[3, 6, 9], [12, 15, 18], [21, 24, 27]])
E = np.array([[4, 8, 12], [16, 20, 24], [28, 32, 36]])
                   
print(check(A, B, C, D, E))

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[2, 4], [8, 10]])
D = np.array([[3, 6, 9], [12, 15, 18]])
E = np.array([[4, 8, 12], [16, 20, 24], [28, 32, 36]])
                   
print(check(A, B, C, D, E))

(True, [3, 3])
(True, [2, 3])
[[1008 1296 1584]
 [2952 3780 4608]]


4.Обчислити вираз:

$$\sum_{i=1}^n(x_{i} - avg(x))^{2}$$

In [57]:
x = np.array([1, 2, 3, 4])
y = np.ones(len(x))

x = (x - x @ y / (y @ y))
print(x*x @ y)

5.0


5. Вивести матрицю, яка при множенні на вектор зліва (Мх) приводить його до форми відхилення від середнього значення. Тобто, кожним елементом вектора-результату буде відповідний елемент вхідного вектора мінус середнє значення. Матриця М не повинна залежати від вхідного вектора x, а лише від його довжини. Іншими словами, для створення такої матриці має бути достатньо лише знання скільки в них елементів.

In [89]:
x = np.array([1, 2, 3, 4])
y = np.ones(len(x))

M = np.full((len(x), len(x)), -1 / len(x))
np.fill_diagonal(M, 1 - 1 / len(x))
print(M)
print(M @ x)

[[ 0.75 -0.25 -0.25 -0.25]
 [-0.25  0.75 -0.25 -0.25]
 [-0.25 -0.25  0.75 -0.25]
 [-0.25 -0.25 -0.25  0.75]]
[-1.5 -0.5  0.5  1.5]


6. Розв'язати систему рівнянь (можна скористатися функцією кореня):

$$
47a^{2} + 71b - 2c = 3\\\
11b - 8c = 3\\\
a^{2} + b + c = 24\\\
$$

In [16]:
import cmath 
A = np.array([[47, 71, -2], [0, 11, -8], [1, 1, 1]])
b = np.array([3, 3, 24]).reshape(-1, 1)

res = np.linalg.solve(A, b).reshape(-1)
res = np.array([list(map(complex, res)), list(map(complex, res))])
res[0][0] = cmath.sqrt(res[0][0])
res[1][0] = -cmath.sqrt(res[1][0])
print(res[0].reshape(-1, 1), res[1].reshape(-1, 1), sep="\n")

[[ 0.        +6.1830856j]
 [26.36023055+0.j       ]
 [35.870317  +0.j       ]]
[[-0.        -6.1830856j]
 [26.36023055+0.j       ]
 [35.870317  +0.j       ]]
